[project]
name = "ezneis"
authors = [
  { name="DuelitDev", email="jyoon07dev@gmail.com" },
]
description = "ezneis: 나이스 API 파싱 라이브러리"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests ~= 2.32.3",
    "aiohttp ~= 3.11.10",
]
keywords = [ "나이스", "neis", "api", "neis-api", "parse", "asyncio" ]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: MIT License",
]
dynamic = ["version", "dependencies"]

[project.urls]
Homepage = "https://github.com/DuelitDev/ezneis"
Download = "https://github.com/DuelitDev/ezneis/tarball/master"
Changelog = "https://github.com/DuelitDev/ezneis/releases"
Documentation = "https://github.com/DuelitDev/ezneis/wiki"
Issues = "https://github.com/DuelitDev/ezneis/issues"

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = {file = ["VERSION"]}
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.packages.find]
where = ["."]
include = ["ezneis*"]
exclude = ["tests"]

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "session"
asyncio_mode = "auto"
